### ISSUE TITLE
Premature Rating Predictions on lccn.lbao.site

### ISSUE THREAD

**Issue by Shrined** [baoliay2008/lccn_predictor#12]
The results of leetcode contests typically require over 15 minutes to account for every participant. However, https://lccn.lbao.site/ consistently predicts ratings before all participants' results are collected. For instance, during today's bi-weekly contest (4/29/2023), the prediction occurred at 11:11:43 AM CDT, but the final participant count was only completed around 11:20 AM. Consequently, the last page of https://lccn.lbao.site/predicted/biweekly-contest-103 displays 12,498 participants, while the actual total was 17,137. This incomplete data leads to inaccurate rating predictions.

**Comment by baoliay2008** [comment]
Greetings @Shrined, thank you for sharing your concern with us.

Please be aware that currently, this application does not include participants who have a score of zero. As an illustration, consider biweekly-contest-103, where you can visit [page 500](https://leetcode.com/contest/biweekly-contest-103/ranking/500/) to observe that 12,498 users have a non-zero score. This is because we are unable to distinguish between users who have not participated and those who have a score of zero, so we cannot calculate the penalties. You can find further details on this matter in the post titled [New Rating Algorithm Details - Contest Season and Absence in Participation](https://leetcode.com/discuss/general-discussion/518516/New-Rating-Algorithm-Details-Contest-Season-and-Absence-in-Participation).

Regarding the time-related matter, I am currently testing a new crawling and data-merging method that may be slightly faster than the LeetCode US site. As I am still testing this method, I will update the codebase and documentation accordingly.

**Comment by Shrined** [comment]
I see. Thanks for the explanation!
